trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformValidate
    displayName: Terraform Validate
    jobs:
      - job: TerraformValidatejob
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            artifact: 'terraform-manifests-out'
            publishLocation: 'pipeline'
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            backendType: 'azurerm'
            backendServiceArm: 'ATS_LABS(a5d9cb3e-8f8a-43d7-8277-56dfbca4bc8b)'
            ensureBackend: true
            backendAzureRmResourceGroupName: 'terraform-storage-rg118'
            backendAzureRmResourceGroupLocation: 'East US'
            backendAzureRmStorageAccountName: 'terraformstate1ats'
            backendAzureRmContainerName: 'tfstatefiles'
            backendAzureRmKey: 'aks.tfstate'
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            allowTelemetryCollection: false
        

